# Site wide configuration

title:            blog do qgustavor
locale:           pt_BR
url:              https://qgustavor.tk


# Jekyll configuration
timezone:    America/Fortaleza
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
kramdown:
  input: GFM

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true

# Site owner
owner:
  name: Gustavo
  avatar: https://i.imgur.com/rkC92f6.png
  bio: "Escrevo sobre programas, animes e um pouco mais."
  email:
  disqus-shortname: qgustavor
  twitter: qgustavor #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: qgustavor #username
  stackoverflow: "1850091/gustavo-rodrigues" #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  myanimelist: #username
  anilist: qgustavor #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
